const BANK_ACCOUNT_STATUS = {
    ACTIVE: "ACTIVE",
    BLOCKED: "BLOCKED"
}

const CARD_STATUS = {
    ACTIVE: "ACTIVE",
    BLOCKED: "BLOCKED"
}

const PAYMENT_STATUS = {
    CREATED: "CREATED",
    CONFIRMED: "CONFIRMED",
    CANCELED: "CANCELED",
}


module.exports = {BANK_ACCOUNT_STATUS, CARD_STATUS, PAYMENT_STATUS}